### ISSUE TITLE
User Journey: Tourist

### ISSUE THREAD

**Issue by Karyum** [FACN1/city-guide#8]
As a tourist who is curious about different landmarks I want to go in the website to find more info about them:

- [x] I want to go to the website and see a map of my location #11 
- [x] I want to able to navigate the map so i can find out what is in my vicinity #12 
- [x] I want to see how many nuggets there are around #13 
- [x] I want to see different type of icons so that i can only click on the ones i'm interested in #14 
- [x] I want to click on an icon on the map and see information. #10 
- [x] I want the info tab to be well laid out so i can read it clearly #15 
- [x] I want to be able to easily close the info tab so I can continue to browse for more #16
