### ISSUE TITLE
User Journey : knowledgeable local

### ISSUE THREAD

**Issue by Karyum** [FACN1/city-guide#9]
I want to share some interesting things about my city so that people can benefit from it

- [x] I want to go to the website and see a map of my location #11
- [x] I want there to be an easily accessible and explicit add button #17 
- [x] After clicking the add button I want it to be easy to place the pin where I want it #18
- [x] I want a well laid out add nugget form #19
- [x] After adding a nugget I want confirmation that it's been successful #20
